// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmXrc5czewGCDLT1c_ueKWSGw60mjktZA',
    appId: '1:816986532792:web:1c6832fb4ed0364e77fd4d',
    messagingSenderId: '816986532792',
    projectId: 'azkar-app-6e628',
    authDomain: 'azkar-app-6e628.firebaseapp.com',
    storageBucket: 'azkar-app-6e628.firebasestorage.app',
    measurementId: 'G-V8PCRRJB9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc1g-R67RGwcxGZ5Af--mhnUsN-1yF0Ik',
    appId: '1:816986532792:android:1d1e757a8c5092e577fd4d',
    messagingSenderId: '816986532792',
    projectId: 'azkar-app-6e628',
    storageBucket: 'azkar-app-6e628.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhGAf40EAdyISrmRMKgnyogKKSl6SBwoA',
    appId: '1:816986532792:ios:02f4c37e99cb373377fd4d',
    messagingSenderId: '816986532792',
    projectId: 'azkar-app-6e628',
    storageBucket: 'azkar-app-6e628.firebasestorage.app',
    iosBundleId: 'com.example.newAzkarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhGAf40EAdyISrmRMKgnyogKKSl6SBwoA',
    appId: '1:816986532792:ios:02f4c37e99cb373377fd4d',
    messagingSenderId: '816986532792',
    projectId: 'azkar-app-6e628',
    storageBucket: 'azkar-app-6e628.firebasestorage.app',
    iosBundleId: 'com.example.newAzkarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmXrc5czewGCDLT1c_ueKWSGw60mjktZA',
    appId: '1:816986532792:web:a7747545345a39cf77fd4d',
    messagingSenderId: '816986532792',
    projectId: 'azkar-app-6e628',
    authDomain: 'azkar-app-6e628.firebaseapp.com',
    storageBucket: 'azkar-app-6e628.firebasestorage.app',
    measurementId: 'G-S9BHTNCNYW',
  );
}


